# Generated by Django 2.2.4 on 2019-08-08 05:44

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to=articles.models.scramble_uploaded_filename, verbose_name='Uploaded Image'),
        ),
    ]
